name: ExampleForRX
options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "com.lyy"
packages:
  SnapKit:
    from: "5.6.0"
    url: "https://github.com/SnapKit/SnapKit.git"
  RxSwift:
    from: "6.6.0"
    url: "https://github.com/ReactiveX/RxSwift.git"
  RxCocoa:
    from: "6.6.0"
    url: "https://github.com/ReactiveX/RxSwift.git"
  Factory:
    from: "2.1.5"
    url: "https://github.com/hmlongco/Factory.git"
targets:
  ExampleForRX:
    type: application
    platform: iOS
    deploymentTarget: "16.1"
    sources:
      - path: ExampleForRX
    settings:
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
    info:
      path: ExampleForRX/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        Application supports indirect input events: YES
        Application requires iPhone environment: YES
        UILaunchScreen: LaunchScreen
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        Supported interface orientations (iPhone): [Portrait (bottom home button), Landscape (left home button), Landscape (right home button), Portrait (top home button)]
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: NO
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - { UISceneConfigurationName: Default Configuration, UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate }
    dependencies:
      - package: SnapKit
      - package: RxSwift
      - package: RxCocoa
      - package: Factory
